/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TVShowTimelineMaker.ui.Event;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.timeConstraints.interfaces.TimeConstraint;
import TVShowTimelineMaker.timeline.EventImp;
import TVShowTimelineMaker.timeline.OnceDayEvent;
import TVShowTimelineMaker.ui.ConstraintEditors.ConstraintEditorWindow;
import TVShowTimelineMaker.ui.Joda.DateTimeEditor;
import com.civprod.swing.CollectionListModel;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.joda.time.DateTime;

/**
 *
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class DayEventEditor extends EventEditorWindow {
    
    @com.civprod.dynamicClassLoading.ClassInitalizer
        public static final void addMe() {
            EventEditorWindow.addEventEditor(OnceDayEvent.class, DayEventEditor.class);
        }

    OnceDayEvent mEvent;
    CollectionListModel<DateTime> SuggestedDaysModel;
    CollectionListModel<TimeConstraint> constraintModel;

    public DayEventEditor() {
        this(new OnceDayEvent());
    }

    /**
     * Creates new form EventEditor
     *
     * @param inEvent
     */
    public DayEventEditor(OnceDayEvent inEvent) {
        this.initComponents();
        this.mEvent = inEvent;
        this.txtName.setText(this.mEvent.getName());
        this.txtEarliestPossibleDate.setText(this.mEvent.getEarliestPossibleDate().toString());
        this.txtLatestPossibleDate.setText(this.mEvent.getLatestPossibleDate().toString());
        this.constraintModel = new CollectionListModel<>(Main.myShow.getTimeLine().getConstraintsOnEvent(inEvent));
        this.listCon.setModel(this.constraintModel);
        this.SuggestedDaysModel = new CollectionListModel<>(this.mEvent.getSuggestedDays());
        this.listSuggestedDays.setModel(this.SuggestedDaysModel);
        this.txtDaysOut.setText(java.lang.Double.toString(this.mEvent.sizeAdj()));
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEarliestPossibleDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLatestPossibleDate = new javax.swing.JLabel();
        cmdEditEarliestPossibleDate = new javax.swing.JButton();
        cmdEditLatestPossibleDate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCon = new javax.swing.JList<TimeConstraint>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSuggestedDays = new javax.swing.JList<DateTime>();
        cmdAddSuggestedDay = new javax.swing.JButton();
        cmdRemoveSuggestedDay = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDaysOut = new javax.swing.JLabel();
        cmdEditConstraint = new javax.swing.JButton();
        cmdDeleteConstraint = new javax.swing.JButton();

        jLabel1.setText("name");

        txtName.setText("jTextField1");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        jLabel2.setText("earliestPossibleDate");

        txtEarliestPossibleDate.setText("jLabel3");

        jLabel3.setText("latestPossibleDate");

        txtLatestPossibleDate.setText("jLabel4");

        cmdEditEarliestPossibleDate.setText("edit earliestPossibleDate");
        cmdEditEarliestPossibleDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditEarliestPossibleDateActionPerformed(evt);
            }
        });

        cmdEditLatestPossibleDate.setText("edit latestPossibleDate");
        cmdEditLatestPossibleDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditLatestPossibleDateActionPerformed(evt);
            }
        });

        listCon.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCon);

        listSuggestedDays.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listSuggestedDays);

        cmdAddSuggestedDay.setText("Add Suggested Day");
        cmdAddSuggestedDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddSuggestedDayActionPerformed(evt);
            }
        });

        cmdRemoveSuggestedDay.setText("Remove Suggested Day");
        cmdRemoveSuggestedDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRemoveSuggestedDayActionPerformed(evt);
            }
        });

        jLabel4.setText("placement days");

        txtDaysOut.setText("jLabel5");

        cmdEditConstraint.setText("edit constraint");
        cmdEditConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditConstraintActionPerformed(evt);
            }
        });

        cmdDeleteConstraint.setText("delete constraint");
        cmdDeleteConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteConstraintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEarliestPossibleDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditEarliestPossibleDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtLatestPossibleDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditLatestPossibleDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdEditConstraint)
                            .addComponent(cmdDeleteConstraint)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdAddSuggestedDay)
                            .addComponent(cmdRemoveSuggestedDay)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDaysOut)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEarliestPossibleDate)
                    .addComponent(cmdEditEarliestPossibleDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLatestPossibleDate)
                    .addComponent(cmdEditLatestPossibleDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAddSuggestedDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdRemoveSuggestedDay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdEditConstraint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteConstraint)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDaysOut)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        this.mEvent.setName(this.txtName.getText());
    }//GEN-LAST:event_txtNameFocusLost

    private void cmdEditEarliestPossibleDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditEarliestPossibleDateActionPerformed
        //create DateTimeEditor, display it and get the DateTime back when it's done
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor(this.mEvent.getEarliestPossibleDate());
        newDateTimeEditor.setVisible(true);
        final DayEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.setEarliestPossibleDate(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdEditEarliestPossibleDateActionPerformed

    private void cmdEditLatestPossibleDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditLatestPossibleDateActionPerformed
        //create DateTimeEditor, display it and get the DateTime back when it's done
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor(this.mEvent.getLatestPossibleDate());
        newDateTimeEditor.setVisible(true);
        final DayEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.setLatestPossibleDate(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdEditLatestPossibleDateActionPerformed

    private void cmdAddSuggestedDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddSuggestedDayActionPerformed
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor();
        newDateTimeEditor.setVisible(true);
        final DayEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.addSuggestedDay(newDateTimeEditor.mDateTime);
                SuggestedDaysModel.add(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdAddSuggestedDayActionPerformed

    private void cmdRemoveSuggestedDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRemoveSuggestedDayActionPerformed
        this.mEvent.removeSuggestedDay(this.listSuggestedDays.getSelectedValue());
        this.SuggestedDaysModel.remove(this.listSuggestedDays.getSelectedValue());
        if (!this.SuggestedDaysModel.isEmpty()) {
            this.listSuggestedDays.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdRemoveSuggestedDayActionPerformed

    private void cmdEditConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditConstraintActionPerformed
        Class<? extends TimeConstraint> SelectedClass = this.listCon.getSelectedValue().getClass();
        Class<? extends ConstraintEditorWindow> constraintEditorClass = ConstraintEditorWindow.getConstraintEditor(SelectedClass);
        ConstraintEditorWindow tempEditorWindow;
        try {
            tempEditorWindow = constraintEditorClass.getConstructor(SelectedClass).newInstance(this.listCon.getSelectedValue());
        } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
            tempEditorWindow = null;
        } catch (InvocationTargetException ex) {
            Logger.getLogger(DayEventEditor.class.getName()).log(Level.SEVERE, null, ex);
            tempEditorWindow = null;
        }
        final ConstraintEditorWindow newEditorWindow = tempEditorWindow;
        if (newEditorWindow != null) {
            newEditorWindow.setVisible(true);
            final javax.swing.JFrame tempThis = this;
            newEditorWindow.runOnClose(new Runnable() {
                @Override
                public void run() {
                    Main.myShow.getTimeLine().removeTimeConstraint(listCon.getSelectedValue());
                    constraintModel.remove(listCon.getSelectedValue());
                    Main.myShow.getTimeLine().addTimeConstraint(newEditorWindow.getValue());
                    constraintModel.add(newEditorWindow.getValue());
                    constraintModel.setSelectedItem(newEditorWindow.getValue());
                    listCon.setSelectedIndex(constraintModel.indexOf(newEditorWindow.getValue()));
                    tempThis.setVisible(true);
                }
            });
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_cmdEditConstraintActionPerformed

    private void cmdDeleteConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteConstraintActionPerformed
        TimeConstraint selectedItem = this.constraintModel.getSelectedItem();
        Object selectedValue = this.listCon.getSelectedValue();
        Main.myShow.getTimeLine().removeTimeConstraint(this.listCon.getSelectedValue());
        this.constraintModel.remove(this.listCon.getSelectedValue());
        if (!this.constraintModel.isEmpty()) {
            this.constraintModel.setSelectedItem(this.constraintModel.get(0));
            this.listCon.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdDeleteConstraintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAddSuggestedDay;
    private javax.swing.JButton cmdDeleteConstraint;
    private javax.swing.JButton cmdEditConstraint;
    private javax.swing.JButton cmdEditEarliestPossibleDate;
    private javax.swing.JButton cmdEditLatestPossibleDate;
    private javax.swing.JButton cmdRemoveSuggestedDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<TimeConstraint> listCon;
    private javax.swing.JList<DateTime> listSuggestedDays;
    private javax.swing.JLabel txtDaysOut;
    private javax.swing.JLabel txtEarliestPossibleDate;
    private javax.swing.JLabel txtLatestPossibleDate;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public EventImp getValue() {
        return this.mEvent;
    }
    private static final Logger LOG = Logger.getLogger(DayEventEditor.class.getName());
}
