/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TVShowTimelineMaker.ui.Event;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.timeConstraints.interfaces.TimeConstraint;
import TVShowTimelineMaker.timeline.EventImp;
import TVShowTimelineMaker.timeline.OncePeriodEvent;
import TVShowTimelineMaker.ui.ConstraintEditors.ConstraintEditorWindow;
import TVShowTimelineMaker.ui.Joda.DateTimeEditor;
import com.civprod.swing.CollectionListModel;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class PeriodEventEditor extends EventEditorWindow {
    private static final long serialVersionUID = 1517L;
    
    @com.civprod.dynamicClassLoading.ClassInitalizer
        public static final void addMe() {
            EventEditorWindow.addEventEditor(OncePeriodEvent.class, PeriodEventEditor.class);
        }
        
        OncePeriodEvent mEvent;
    CollectionListModel<TimeConstraint> constraintModel;

    /**
     * Creates new form PeriodEventEditor
     */
    public PeriodEventEditor() {
        this(new OncePeriodEvent());
    }
    
    public PeriodEventEditor(OncePeriodEvent inEvent){
        this.initComponents();
        this.mEvent = inEvent;
        this.txtName.setText(this.mEvent.getName());
        this.txtEarliestPossibleDateForStart.setText(this.mEvent.getEarliestPossibleStartTime().toString());
        this.txtLatestPossibleDateForStart.setText(this.mEvent.getLatestPossibleStartTime().toString());
        this.txtEarliestPossibleDateForEnd.setText(this.mEvent.getEarliestPossibleEndTime().toString());
        this.txtLatestPossibleDateForEnd.setText(this.mEvent.getLatestPossibleEndTime().toString());
        javax.swing.SpinnerNumberModel minModel = (javax.swing.SpinnerNumberModel) this.spinMinDuration.getModel();
        minModel.setValue(this.mEvent.getMinDuration());
        javax.swing.SpinnerNumberModel maxModel = (javax.swing.SpinnerNumberModel) this.spinMaxDuration.getModel();
        maxModel.setValue(this.mEvent.getMaxDuration());
        this.constraintModel = new CollectionListModel<>(Main.myShow.getTimeLine().getConstraintsOnEvent(inEvent));
        this.listCon.setModel(this.constraintModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEarliestPossibleDateForStart = new javax.swing.JLabel();
        cmdEditEarliestPossibleDateForStart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtLatestPossibleDateForStart = new javax.swing.JLabel();
        cmdEditLatestPossibleDateForStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCon = new javax.swing.JList<TimeConstraint>();
        jLabel4 = new javax.swing.JLabel();
        txtEarliestPossibleDateForEnd = new javax.swing.JLabel();
        cmdEditEarliestPossibleDateForEnd = new javax.swing.JButton();
        cmdEditLatestPossibleDateForEnd = new javax.swing.JButton();
        txtLatestPossibleDateForEnd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spinMinDuration = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        spinMaxDuration = new javax.swing.JSpinner();
        cmdEditConstraint = new javax.swing.JButton();
        cmdDeleteConstraint = new javax.swing.JButton();

        jLabel1.setText("name");

        txtName.setText("jTextField1");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        jLabel2.setText("earliestPossibleDateForStart");

        txtEarliestPossibleDateForStart.setText("jLabel3");

        cmdEditEarliestPossibleDateForStart.setText("edit earliestPossibleDateForStart");
        cmdEditEarliestPossibleDateForStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditEarliestPossibleDateForStartActionPerformed(evt);
            }
        });

        jLabel3.setText("latestPossibleDateForStart");

        txtLatestPossibleDateForStart.setText("jLabel4");

        cmdEditLatestPossibleDateForStart.setText("edit latestPossibleDateForStart");
        cmdEditLatestPossibleDateForStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditLatestPossibleDateForStartActionPerformed(evt);
            }
        });

        listCon.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listCon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listCon);

        jLabel4.setText("earliestPossibleDateForEnd");

        txtEarliestPossibleDateForEnd.setText("jLabel3");

        cmdEditEarliestPossibleDateForEnd.setText("edit earliestPossibleDateForEnd");
        cmdEditEarliestPossibleDateForEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditEarliestPossibleDateForEndActionPerformed(evt);
            }
        });

        cmdEditLatestPossibleDateForEnd.setText("edit latestPossibleDateForEnd");
        cmdEditLatestPossibleDateForEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditLatestPossibleDateForEndActionPerformed(evt);
            }
        });

        txtLatestPossibleDateForEnd.setText("jLabel4");

        jLabel5.setText("latestPossibleDateForEnd");

        jLabel6.setText("minumum Duration");

        spinMinDuration.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinMinDuration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinMinDurationFocusLost(evt);
            }
        });

        jLabel7.setText("maximum Duration");

        spinMaxDuration.setModel(new javax.swing.SpinnerNumberModel());
        spinMaxDuration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinMaxDurationFocusLost(evt);
            }
        });

        cmdEditConstraint.setText("edit constraint");
        cmdEditConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditConstraintActionPerformed(evt);
            }
        });

        cmdDeleteConstraint.setText("delete constraint");
        cmdDeleteConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteConstraintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEarliestPossibleDateForEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditEarliestPossibleDateForEnd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtLatestPossibleDateForEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditLatestPossibleDateForEnd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEarliestPossibleDateForStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditEarliestPossibleDateForStart))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtLatestPossibleDateForStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditLatestPossibleDateForStart))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdEditConstraint)
                            .addComponent(cmdDeleteConstraint)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spinMaxDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spinMinDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEarliestPossibleDateForStart)
                    .addComponent(cmdEditEarliestPossibleDateForStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLatestPossibleDateForStart)
                    .addComponent(cmdEditLatestPossibleDateForStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEarliestPossibleDateForEnd)
                    .addComponent(cmdEditEarliestPossibleDateForEnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLatestPossibleDateForEnd)
                    .addComponent(cmdEditLatestPossibleDateForEnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinMinDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinMaxDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdEditConstraint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteConstraint)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(383, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        this.mEvent.setName(this.txtName.getText());
    }//GEN-LAST:event_txtNameFocusLost

    private void cmdEditEarliestPossibleDateForStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditEarliestPossibleDateForStartActionPerformed
        //create DateTimeEditor, display it and get the DateTime back when it's done
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor(this.mEvent.getEarliestPossibleStartTime());
        newDateTimeEditor.setVisible(true);
        final PeriodEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.setEarliestPossibleDateForStart(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdEditEarliestPossibleDateForStartActionPerformed

    private void cmdEditLatestPossibleDateForStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditLatestPossibleDateForStartActionPerformed
        //create DateTimeEditor, display it and get the DateTime back when it's done
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor(this.mEvent.getLatestPossibleStartTime());
        newDateTimeEditor.setVisible(true);
        final PeriodEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.setLatestPossibleDateForStart(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdEditLatestPossibleDateForStartActionPerformed

    private void cmdEditEarliestPossibleDateForEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditEarliestPossibleDateForEndActionPerformed
        //create DateTimeEditor, display it and get the DateTime back when it's done
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor(this.mEvent.getEarliestPossibleEndTime());
        newDateTimeEditor.setVisible(true);
        final PeriodEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.setEarliestPossibleDateForEnd(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdEditEarliestPossibleDateForEndActionPerformed

    private void cmdEditLatestPossibleDateForEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditLatestPossibleDateForEndActionPerformed
        //create DateTimeEditor, display it and get the DateTime back when it's done
        this.setVisible(false);
        final DateTimeEditor newDateTimeEditor = new DateTimeEditor(this.mEvent.getLatestPossibleEndTime());
        newDateTimeEditor.setVisible(true);
        final PeriodEventEditor tempThis = this;
        newDateTimeEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mEvent.setLatestPossibleDateForEnd(newDateTimeEditor.mDateTime);
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cmdEditLatestPossibleDateForEndActionPerformed

    private void spinMinDurationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinMinDurationFocusLost
        this.mEvent.setMinDuration((java.lang.Integer) this.spinMinDuration.getModel().getValue());
    }//GEN-LAST:event_spinMinDurationFocusLost

    private void spinMaxDurationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinMaxDurationFocusLost
        this.mEvent.setMaxDuration((java.lang.Integer) this.spinMaxDuration.getModel().getValue());
    }//GEN-LAST:event_spinMaxDurationFocusLost

    private void cmdEditConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditConstraintActionPerformed
        Class<? extends TimeConstraint> SelectedClass = this.listCon.getSelectedValue().getClass();
        Class<? extends ConstraintEditorWindow> constraintEditorClass = ConstraintEditorWindow.getConstraintEditor(SelectedClass);
        ConstraintEditorWindow tempEditorWindow;
        try {
            tempEditorWindow = constraintEditorClass.getConstructor(SelectedClass).newInstance(this.listCon.getSelectedValue());
        } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
            tempEditorWindow = null;
        } 
        final ConstraintEditorWindow newEditorWindow = tempEditorWindow;
        if (newEditorWindow != null) {
            newEditorWindow.setVisible(true);
            final javax.swing.JFrame tempThis = this;
            newEditorWindow.runOnClose(new Runnable() {
                @Override
                public void run() {
                    Main.myShow.getTimeLine().removeTimeConstraint(listCon.getSelectedValue());
                    constraintModel.remove(listCon.getSelectedValue());
                    Main.myShow.getTimeLine().addTimeConstraint(newEditorWindow.getValue());
                    constraintModel.add(newEditorWindow.getValue());
                    constraintModel.setSelectedItem(newEditorWindow.getValue());
                    listCon.setSelectedIndex(constraintModel.indexOf(newEditorWindow.getValue()));
                    tempThis.setVisible(true);
                }
            });
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_cmdEditConstraintActionPerformed

    private void cmdDeleteConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteConstraintActionPerformed
        TimeConstraint selectedItem = this.constraintModel.getSelectedItem();
        Object selectedValue = this.listCon.getSelectedValue();
        Main.myShow.getTimeLine().removeTimeConstraint(this.listCon.getSelectedValue());
        this.constraintModel.remove(this.listCon.getSelectedValue());
        if (!this.constraintModel.isEmpty()) {
            this.constraintModel.setSelectedItem(this.constraintModel.get(0));
            this.listCon.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdDeleteConstraintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeriodEventEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PeriodEventEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDeleteConstraint;
    private javax.swing.JButton cmdEditConstraint;
    private javax.swing.JButton cmdEditEarliestPossibleDateForEnd;
    private javax.swing.JButton cmdEditEarliestPossibleDateForStart;
    private javax.swing.JButton cmdEditLatestPossibleDateForEnd;
    private javax.swing.JButton cmdEditLatestPossibleDateForStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<TimeConstraint> listCon;
    private javax.swing.JSpinner spinMaxDuration;
    private javax.swing.JSpinner spinMinDuration;
    private javax.swing.JLabel txtEarliestPossibleDateForEnd;
    private javax.swing.JLabel txtEarliestPossibleDateForStart;
    private javax.swing.JLabel txtLatestPossibleDateForEnd;
    private javax.swing.JLabel txtLatestPossibleDateForStart;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public EventImp getValue() {
        return this.mEvent;
    }
    private static final Logger LOG = Logger.getLogger(PeriodEventEditor.class.getName());
}
