/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TVShowTimelineMaker.ui;

import java.awt.Graphics;
import java.util.logging.Handler;
import java.util.logging.LogRecord;
import java.util.logging.Logger;


public final class LogWindow extends javax.swing.JFrame {
    
    java.util.concurrent.atomic.AtomicReference<String> newText = new java.util.concurrent.atomic.AtomicReference<>();

    /**
     * Creates new form LogWindow
     */
    private LogWindow() {
        this.initComponents();
        this.newText.set("");
    }
    
    @Override
    public void paint(Graphics g) {
        this.txtLogOut.setText(this.newText.get());
        super.paint(g);
    }
    
    private static final LogWindow mInstance = new LogWindow();
    
    public static LogWindow getGobalWindow(){
        return mInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        txtLogOut.setColumns(20);
        txtLogOut.setLineWrap(true);
        txtLogOut.setRows(5);
        jScrollPane1.setViewportView(txtLogOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LogWindow().setVisible(true);
            }
        });
    }
    
    public Handler getLogHandler(){
        return new LogWindowHandler();
    }
    
    public final class LogWindowHandler extends Handler {

        @Override
        public void publish(LogRecord record) {
            if (this.getFormatter() == null) {
                this.setFormatter(new java.util.logging.SimpleFormatter());
            }
            StringBuilder sOut = new StringBuilder(newText.get());
            if (this.getFormatter() != null) {
                sOut.append(this.getFormatter().formatMessage(record));
            } else {
                sOut.append(record.getMessage());
            }
            sOut.append("\n");
            String rValue = sOut.toString();
            newText.set(rValue);
        }

        @Override
        public void flush() {
            
        }

        @Override
        public void close() throws SecurityException {
            
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public final javax.swing.JTextArea txtLogOut = new javax.swing.JTextArea();
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(LogWindow.class.getName());
}
