/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TVShowTimelineMaker.ui;

import TVShowTimelineMaker.Show;
import TVShowTimelineMaker.character.NamedCharacter;
import TVShowTimelineMaker.timeline.Episode;
import TVShowTimelineMaker.util.XML.TopLevelXMLWriter;
import com.civprod.swing.CollectionListModel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class ShowEditor extends javax.swing.JFrame {

    Show mShow;
    CollectionListModel<NamedCharacter> characterModel;
    CollectionListModel<Episode> episodeModel;

    /**
     *
     */
    public ShowEditor() {
        this(TVShowTimelineMaker.Main.myShow);
    }

    /**
     * Creates new form ShowEditor
     * @param inShow
     */
    public ShowEditor(Show inShow) {
        this.initComponents();
        this.mShow = inShow;
        this.characterModel = new CollectionListModel<>(this.mShow.getCharacters());
        this.listCharacter.setModel(this.characterModel);
        if (!this.characterModel.isEmpty()) {
            this.characterModel.setSelectedItem(this.characterModel.get(0));
            this.listCharacter.setSelectedIndex(0);
        }
        this.episodeModel = new CollectionListModel<>(this.mShow.getEpisodes());
        this.listEpisode.setModel(this.episodeModel);
        if (!this.episodeModel.isEmpty()) {
            this.episodeModel.setSelectedItem(this.episodeModel.get(0));
            this.listEpisode.setSelectedIndex(0);
        }
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCharacter = new javax.swing.JList<NamedCharacter>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEpisode = new javax.swing.JList<Episode>();
        cmdAddCharacter = new javax.swing.JButton();
        cmdEditCharacter = new javax.swing.JButton();
        cmdDeleteCharacter = new javax.swing.JButton();
        cmdCreateEpisode = new javax.swing.JButton();
        cmdEditEpisode = new javax.swing.JButton();
        cmdDeleteEpisode = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();
        txtFileName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listCharacter.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCharacter);

        listEpisode.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEpisode);

        cmdAddCharacter.setText("add character");
        cmdAddCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddCharacterActionPerformed(evt);
            }
        });

        cmdEditCharacter.setText("edit character");
        cmdEditCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditCharacterActionPerformed(evt);
            }
        });

        cmdDeleteCharacter.setText("delete character");
        cmdDeleteCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteCharacterActionPerformed(evt);
            }
        });

        cmdCreateEpisode.setText("add episode");
        cmdCreateEpisode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateEpisodeActionPerformed(evt);
            }
        });

        cmdEditEpisode.setText("edit episode");
        cmdEditEpisode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditEpisodeActionPerformed(evt);
            }
        });

        cmdDeleteEpisode.setText("delete Episode");
        cmdDeleteEpisode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteEpisodeActionPerformed(evt);
            }
        });

        cmdSave.setText("save show");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        txtFileName.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdCreateEpisode)
                            .addComponent(cmdEditEpisode)
                            .addComponent(cmdDeleteEpisode)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmdSave))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmdAddCharacter)
                                .addComponent(cmdEditCharacter)
                                .addComponent(cmdDeleteCharacter)))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAddCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteCharacter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdCreateEpisode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditEpisode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteEpisode)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSave)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAddCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddCharacterActionPerformed
        this.setVisible(false);
        final CharacterEditor newCharacterEditor = new CharacterEditor();
        newCharacterEditor.setVisible(true);
        final javax.swing.JFrame tempThis = this;
        newCharacterEditor.runOnClose(() -> {
            mShow.addCharacter(newCharacterEditor.mNamedCharacter);
            characterModel.add(newCharacterEditor.mNamedCharacter);
            tempThis.setVisible(true);
        });
    }//GEN-LAST:event_cmdAddCharacterActionPerformed

    private void cmdEditCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditCharacterActionPerformed
        this.setVisible(false);
        CharacterEditor newCharacterEditor = new CharacterEditor(this.listCharacter.getSelectedValue());
        newCharacterEditor.setVisible(true);
        final javax.swing.JFrame tempThis = this;
        newCharacterEditor.runOnClose(() -> {
            tempThis.setVisible(true);
        });
    }//GEN-LAST:event_cmdEditCharacterActionPerformed

    private void cmdDeleteCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteCharacterActionPerformed
        this.mShow.removeCharacter(this.listCharacter.getSelectedValue());
        this.characterModel.remove(this.listCharacter.getSelectedValue());
        if (!this.characterModel.isEmpty()) {
            this.characterModel.setSelectedItem(this.characterModel.get(0));
            this.listCharacter.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdDeleteCharacterActionPerformed

    private void cmdCreateEpisodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateEpisodeActionPerformed
        this.setVisible(false);
        final EpisodeEditor newEpisodeEditor = new EpisodeEditor();
        final javax.swing.JFrame tempThis = this;
        newEpisodeEditor.runOnClose(() -> {
            mShow.addEpisode(newEpisodeEditor.mEpisode);
            episodeModel.add(newEpisodeEditor.mEpisode);
            tempThis.setVisible(true);
        });
        newEpisodeEditor.setVisible(true);
    }//GEN-LAST:event_cmdCreateEpisodeActionPerformed

    private void cmdEditEpisodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditEpisodeActionPerformed
        this.setVisible(false);
        EpisodeEditor newEpisodeEditor = new EpisodeEditor(this.listEpisode.getSelectedValue());
        newEpisodeEditor.setVisible(true);
        final javax.swing.JFrame tempThis = this;
        newEpisodeEditor.runOnClose(() -> {
            tempThis.setVisible(true);
        });
    }//GEN-LAST:event_cmdEditEpisodeActionPerformed

    private void cmdDeleteEpisodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteEpisodeActionPerformed
        this.mShow.removeEpisode(this.listEpisode.getSelectedValue());
        this.episodeModel.remove(this.listEpisode.getSelectedValue());
        if (!this.episodeModel.isEmpty()) {
            this.episodeModel.setSelectedItem(this.episodeModel.get(0));
            this.listEpisode.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdDeleteEpisodeActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        try {
            TopLevelXMLWriter.writeXMLFile(this.txtFileName.getText(), this.mShow);
        } catch (IOException ex) {
            Logger.getLogger(ShowEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ShowEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAddCharacter;
    private javax.swing.JButton cmdCreateEpisode;
    private javax.swing.JButton cmdDeleteCharacter;
    private javax.swing.JButton cmdDeleteEpisode;
    private javax.swing.JButton cmdEditCharacter;
    private javax.swing.JButton cmdEditEpisode;
    private javax.swing.JButton cmdSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<NamedCharacter> listCharacter;
    private javax.swing.JList<Episode> listEpisode;
    private javax.swing.JTextField txtFileName;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(ShowEditor.class.getName());
}
