/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TVShowTimelineMaker.ui;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.Show;
import TVShowTimelineMaker.util.XML.TopLevelXMLWriter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jdom2.JDOMException;


public class StartWindow extends javax.swing.JFrame {
    private static final long serialVersionUID = 1521L;

    /**
     * Creates new form StartWindow
     */
    public StartWindow() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mFileChooser = new javax.swing.JFileChooser();
        txtNewFile = new javax.swing.JTextField();
        cmdCreate = new javax.swing.JButton();
        cmdOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNewFile.setText("jTextField1");

        cmdCreate.setText("create new file");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });

        cmdOpen.setText("open");
        cmdOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdOpen)
                    .addComponent(cmdCreate))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdOpen)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        String fileName = this.txtNewFile.getText();
        File newXmlFile = new File(this.txtNewFile.getText());
        String nameSpace = fileName.substring(0, fileName.lastIndexOf('.'));
        Main.xmlWriter = new TopLevelXMLWriter(newXmlFile);
        TopLevelXMLWriter.defualtNameSpace = nameSpace;
        Main.myShow = new Show(nameSpace);
        Runtime.getRuntime().addShutdownHook(new Thread(new Main.shutDownWriter()));
        TimeLineEditor newTimeLineEditor = new TimeLineEditor();
        ShowEditor newShowEditor = new ShowEditor();
        newTimeLineEditor.setVisible(true);
        newShowEditor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void cmdOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOpenActionPerformed
        final StartWindow tempthis = this;
        Thread newThread = new Thread(() -> {
            int returnval = tempthis.mFileChooser.showOpenDialog(tempthis);
            if (returnval == JFileChooser.APPROVE_OPTION) {
                File selectedFile = tempthis.mFileChooser.getSelectedFile();
                Main.xmlWriter = new TopLevelXMLWriter(selectedFile);
                Main.myShow = null;
                if (selectedFile.exists()) {
                    try {
                        Main.myShow = Main.xmlWriter.readXMLFile();
                    } catch (JDOMException | IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (Main.myShow == null) {
                    Main.myShow = new Show(TopLevelXMLWriter.defualtNameSpace);
                }
                Runtime.getRuntime().addShutdownHook(new Thread(new Main.shutDownWriter()));
                TimeLineEditor newTimeLineEditor = new TimeLineEditor();
                ShowEditor newShowEditor = new ShowEditor();
                newTimeLineEditor.setVisible(true);
                newShowEditor.setVisible(true);
            } else {
                tempthis.setVisible(true);
            }
        });
        newThread.start();
        this.setVisible(false);
    }//GEN-LAST:event_cmdOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCreate;
    private javax.swing.JButton cmdOpen;
    private javax.swing.JFileChooser mFileChooser;
    private javax.swing.JTextField txtNewFile;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(StartWindow.class.getName());
}
