/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TVShowTimelineMaker.ui;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.timeConstraints.interfaces.TimeConstraint;
import TVShowTimelineMaker.timeline.Event;
import TVShowTimelineMaker.timeline.EventContainer;
import static TVShowTimelineMaker.timeline.EventContainer.UNSATISFIABLE_CONSTRAINTS;
import TVShowTimelineMaker.timeline.OnceDayEvent;
import TVShowTimelineMaker.timeline.OnceEvent;
import TVShowTimelineMaker.timeline.OncePeriodEvent;
import TVShowTimelineMaker.timeline.Timeline;
import TVShowTimelineMaker.timeline.YearlyEvent;
import TVShowTimelineMaker.ui.ConstraintEditors.ConstraintEditorWindow;
import TVShowTimelineMaker.ui.Event.EventEditorWindow;
import TVShowTimelineMaker.util.MapIntegerComparator;
import TVShowTimelineMaker.util.MyLittePonyMaps;
import com.civprod.swing.CollectionListModel;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.joda.time.DateTime;

/**
 *
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class TimeLineEditor extends javax.swing.JFrame {
    
    static {
        Logger.getLogger(TimeLineEditor.class.getName()).setParent(Main.AppGlobalLogger);
        Logger.getLogger(TimeLineEditor.class.getName()).setUseParentHandlers(true);
    }

    Timeline mTimeline;
    CollectionListModel<Event> eventModel;
    CollectionListModel<TimeConstraint> constraintModel;
    

    public TimeLineEditor() {
        this(Main.myShow.getTimeLine());
    }

    /**
     * Creates new form TimeLineEditor
     *
     * @param inTimeline
     */
    public TimeLineEditor(Timeline inTimeline) {
        this.initComponents();
        this.mTimeline = inTimeline;
        this.eventModel = new CollectionListModel<>(this.mTimeline.getEvents());
        this.listEvent.setModel(this.eventModel);
        if (!this.eventModel.isEmpty()) {
            this.eventModel.setSelectedItem(this.eventModel.get(0));
            this.listEvent.setSelectedIndex(0);
        }
        this.constraintModel = new CollectionListModel<>(this.mTimeline.getConstraints());
        this.listConstraints.setModel(this.constraintModel);
        if (!this.constraintModel.isEmpty()) {
            this.constraintModel.setSelectedItem(this.constraintModel.get(0));
            this.listConstraints.setSelectedIndex(0);
        }
        this.comBoxConstraintType.setModel(new CollectionListModel<>(MyLittePonyMaps.getFriendlyStringsForConstraintClasses()));
        this.comBoxEventTypes.setModel(new CollectionListModel<>(MyLittePonyMaps.getFriendlyStringsForEventClasses()));
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listEvent = new javax.swing.JList<TVShowTimelineMaker.timeline.Event>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listConstraints = new javax.swing.JList<TimeConstraint>();
        cmdCreateEvent = new javax.swing.JButton();
        cmdEditEvent = new javax.swing.JButton();
        cmdDeleteEvent = new javax.swing.JButton();
        comBoxConstraintType = new javax.swing.JComboBox<String>();
        createConstraint = new javax.swing.JButton();
        cmdEditConstraint = new javax.swing.JButton();
        cmdDeleteConstraint = new javax.swing.JButton();
        cmdResetTimeline = new javax.swing.JButton();
        cmdPrintPossibleTimeline = new javax.swing.JButton();
        cmdApply = new javax.swing.JButton();
        comBoxEventTypes = new javax.swing.JComboBox<String>();
        cmdPrintRelations = new javax.swing.JButton();
        cmdCircleCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdTimeFrameTest = new javax.swing.JButton();
        cmdRefresh = new javax.swing.JButton();
        cmdBigest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listEvent.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listEvent);

        listConstraints.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listConstraints.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listConstraints);

        cmdCreateEvent.setText("create new event");
        cmdCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateEventActionPerformed(evt);
            }
        });

        cmdEditEvent.setText("edit Event");
        cmdEditEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditEventActionPerformed(evt);
            }
        });

        cmdDeleteEvent.setText("Delete Event");
        cmdDeleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteEventActionPerformed(evt);
            }
        });

        comBoxConstraintType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Relation", "IntervalConstraint", "PartialTimeConstraint", "CharacterRelation" }));

        createConstraint.setText("create new constraint");
        createConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConstraintActionPerformed(evt);
            }
        });

        cmdEditConstraint.setText("edit constraint");
        cmdEditConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditConstraintActionPerformed(evt);
            }
        });

        cmdDeleteConstraint.setText("delete constraint");
        cmdDeleteConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteConstraintActionPerformed(evt);
            }
        });

        cmdResetTimeline.setText("reset timeline");
        cmdResetTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetTimelineActionPerformed(evt);
            }
        });

        cmdPrintPossibleTimeline.setText("Print Possible Timeline");
        cmdPrintPossibleTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintPossibleTimelineActionPerformed(evt);
            }
        });

        cmdApply.setText("Apply constrisnts");
        cmdApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdApplyActionPerformed(evt);
            }
        });

        comBoxEventTypes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DayEvent", "PeriodEvent" }));

        cmdPrintRelations.setText("Print Relations");
        cmdPrintRelations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintRelationsActionPerformed(evt);
            }
        });

        cmdCircleCheck.setText("preform circle check");
        cmdCircleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCircleCheckActionPerformed(evt);
            }
        });

        jLabel1.setText("debug");

        cmdTimeFrameTest.setText("preform timeframe test");
        cmdTimeFrameTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimeFrameTestActionPerformed(evt);
            }
        });

        cmdRefresh.setText("temp button: refresh constraints");
        cmdRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefreshActionPerformed(evt);
            }
        });

        cmdBigest.setText("printBiggestEvents");
        cmdBigest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBigestActionPerformed(evt);
            }
        });

        jButton1.setText("check subset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdEditEvent)
                            .addComponent(cmdDeleteEvent)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comBoxEventTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdCreateEvent))
                            .addComponent(cmdPrintRelations)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdResetTimeline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdApply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrintPossibleTimeline))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comBoxConstraintType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createConstraint))
                            .addComponent(cmdEditConstraint)
                            .addComponent(cmdDeleteConstraint)
                            .addComponent(cmdRefresh)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdCircleCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBigest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdTimeFrameTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comBoxEventTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCreateEvent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditEvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteEvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrintRelations)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comBoxConstraintType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createConstraint))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditConstraint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteConstraint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdRefresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdResetTimeline)
                    .addComponent(cmdApply)
                    .addComponent(cmdPrintPossibleTimeline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCircleCheck)
                    .addComponent(cmdTimeFrameTest)
                    .addComponent(cmdBigest)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateEventActionPerformed
        final javax.swing.JFrame tempThis = this;
        String selectedItem = (String) this.comBoxEventTypes.getSelectedItem();
        Class<? extends EventEditorWindow> constraintEditorClass = EventEditorWindow.getEventEditor(selectedItem);
        EventEditorWindow tempEventEditor;
        try {
            tempEventEditor = constraintEditorClass.newInstance();
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
            tempEventEditor = null;
        }
        final EventEditorWindow newEventEditor = tempEventEditor;
        if (newEventEditor != null) {
            this.setVisible(false);
            newEventEditor.runOnClose(() -> {
                mTimeline.addEvent(newEventEditor.getValue());
                eventModel.add(newEventEditor.getValue());
                tempThis.setVisible(true);
            });
            newEventEditor.setVisible(true);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_cmdCreateEventActionPerformed

    private void cmdEditEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditEventActionPerformed
        final javax.swing.JFrame tempThis = this;
        EventEditorWindow tempEventEditor;
        try {
            Event selectedEvent = this.listEvent.getSelectedValue();
            Class<? extends Event> selectedClass = selectedEvent.getClass();
            Class<? extends EventEditorWindow> eventEditorClass = EventEditorWindow.getEventEditor(selectedClass);
            tempEventEditor = eventEditorClass.getConstructor(selectedClass).newInstance(selectedEvent);
        } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
            tempEventEditor = null;
        }
        final EventEditorWindow newEventEditor = tempEventEditor;
        if (newEventEditor != null) {
            this.setVisible(false);
            newEventEditor.runOnClose(() -> {
                tempThis.setVisible(true);
            });
            newEventEditor.setVisible(true);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_cmdEditEventActionPerformed

    private void cmdDeleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteEventActionPerformed
        this.mTimeline.removeEvent(this.listEvent.getSelectedValue());
        this.eventModel.remove(this.listEvent.getSelectedValue());
        if (!this.eventModel.isEmpty()) {
            this.eventModel.setSelectedItem(this.eventModel.get(0));
            this.listEvent.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdDeleteEventActionPerformed

    private void createConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConstraintActionPerformed
        String selectedItem = (String) this.comBoxConstraintType.getSelectedItem();
        Class<? extends ConstraintEditorWindow> constraintEditorClass = ConstraintEditorWindow.getConstraintEditor(selectedItem);
        ConstraintEditorWindow tempEditorWindow;
        try {
            tempEditorWindow = constraintEditorClass.newInstance();
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
            tempEditorWindow = null;
        }
        final ConstraintEditorWindow newEditorWindow = tempEditorWindow;
        if (newEditorWindow != null) {
            newEditorWindow.setVisible(true);
            final javax.swing.JFrame tempThis = this;
            newEditorWindow.runOnClose(() -> {
                mTimeline.addTimeConstraint(newEditorWindow.getValue());
                constraintModel.add(newEditorWindow.getValue());
                tempThis.setVisible(true);
            });
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_createConstraintActionPerformed

    private void cmdEditConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditConstraintActionPerformed
        Class<? extends TimeConstraint> SelectedClass = this.listConstraints.getSelectedValue().getClass();
        Class<? extends ConstraintEditorWindow> constraintEditorClass = ConstraintEditorWindow.getConstraintEditor(SelectedClass);
        ConstraintEditorWindow tempEditorWindow;
        try {
            tempEditorWindow = constraintEditorClass.getConstructor(SelectedClass).newInstance(this.listConstraints.getSelectedValue());
        } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
            tempEditorWindow = null;
        }
        final ConstraintEditorWindow newEditorWindow = tempEditorWindow;
        if (newEditorWindow != null) {
            newEditorWindow.setVisible(true);
            final javax.swing.JFrame tempThis = this;
            newEditorWindow.runOnClose(() -> {
                mTimeline.removeTimeConstraint(listConstraints.getSelectedValue());
                constraintModel.remove(listConstraints.getSelectedValue());
                mTimeline.addTimeConstraint(newEditorWindow.getValue());
                constraintModel.add(newEditorWindow.getValue());
                constraintModel.setSelectedItem(newEditorWindow.getValue());
                listConstraints.setSelectedIndex(constraintModel.indexOf(newEditorWindow.getValue()));
                tempThis.setVisible(true);
            });
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_cmdEditConstraintActionPerformed

    private void cmdDeleteConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteConstraintActionPerformed
        TimeConstraint selectedItem = this.constraintModel.getSelectedItem();
        Object selectedValue = this.listConstraints.getSelectedValue();
        this.mTimeline.removeTimeConstraint(this.listConstraints.getSelectedValue());
        this.constraintModel.remove(this.listConstraints.getSelectedValue());
        if (!this.constraintModel.isEmpty()) {
            this.constraintModel.setSelectedItem(this.constraintModel.get(0));
            this.listConstraints.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmdDeleteConstraintActionPerformed

    private void cmdResetTimelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetTimelineActionPerformed
        this.mTimeline.resetEvents();
        this.step = 0;
    }//GEN-LAST:event_cmdResetTimelineActionPerformed

    private void cmdPrintPossibleTimelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintPossibleTimelineActionPerformed
        new Thread(() -> {
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("place");
            int finalState = mTimeline.placeEvents();
            //int finalState = mTimeline.placeEventsNew();
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).log(Level.INFO, "state{0}", java.lang.Integer.toString(finalState));
            if (finalState == Timeline.SUCCESS) {
                int initSize = (int)Math.pow(mTimeline.getNumberOfEvents(), .5);
                List<OnceEvent> tempOnceList = new java.util.ArrayList<>(initSize);
                List<YearlyEvent> tempYearlyList = new java.util.ArrayList<>(0);
                for (Event curEvent : mTimeline.getEvents()) {
                    if (curEvent instanceof OnceEvent) {
                        tempOnceList.add((OnceEvent) curEvent);
                    } else if (curEvent instanceof YearlyEvent) {
                        tempYearlyList.add((YearlyEvent) curEvent);
                    }
                }
                java.util.Collections.sort(tempOnceList);
                java.util.Collections.sort(tempYearlyList);
                java.io.BufferedWriter fout = null;
                try {
                    fout = new java.io.BufferedWriter(new java.io.FileWriter("output.txt"));
                    for (OnceEvent curEvent : tempOnceList) {
                        fout.write(curEvent.getName() + " happens " + curEvent.toTimeFrameString() + "\n");
                    }
                    fout.newLine();
                    for (YearlyEvent curEvent : tempYearlyList) {
                        fout.write(curEvent.getName() + " happens " + curEvent.toTimeFrameString() + "\n");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        if (fout != null) {
                            fout.flush();
                            fout.close();
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("done");
        }).start();
    }//GEN-LAST:event_cmdPrintPossibleTimelineActionPerformed

    int step = 0;
    private void cmdApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdApplyActionPerformed
        new Thread(() -> {
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("start");
            int state1 = 0;
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("level 1");
            if (mTimeline.applyConstraintsLevel1Sure(java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()))) {
                state1 = UNSATISFIABLE_CONSTRAINTS;
            }
            if ((state1 == 0) && (step > 0)) {
                java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("level 2");
                Collection<Event> events = mTimeline.getEvents();
                events.stream().forEach((curEvent) -> {
                    curEvent.setUpForComplexEval();
                });
                int rState = mTimeline.applyConstraintsLevel2Sure(java.util.logging.Logger.getLogger(Timeline.class.getName()), true);
                if (rState == 1) {
                    state1 = UNSATISFIABLE_CONSTRAINTS;
                } else if (rState == Timeline.FAILURE) {
                    state1 = Timeline.FAILURE;
                }
            }
            if ((state1 == 0) && (step > 1)) {
                java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("level 3");
                if (mTimeline.applyConstraintsLevel3Branch(java.util.logging.Logger.getLogger(Timeline.class.getName()))) {
                    state1 = UNSATISFIABLE_CONSTRAINTS;
                }
            }
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).log(Level.INFO, "state{0}", java.lang.Integer.toString(state1));
            step++;
        }).start();
    }//GEN-LAST:event_cmdApplyActionPerformed

    private void cmdPrintRelationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintRelationsActionPerformed
        Event selectedValue = this.listEvent.getSelectedValue();
        if (selectedValue instanceof OnceEvent) {
            OnceEvent selectedOnceEvent = (OnceEvent) selectedValue;
            Collection<OnceEvent> afterEventAre = this.mTimeline.afterEventAre(selectedOnceEvent);
            Collection<OnceEvent> beforeEventAre = this.mTimeline.beforeEventAre(selectedOnceEvent);
            Collection<OnceEvent> afterEventCouldBe = this.mTimeline.afterEventCouldBe(selectedOnceEvent);
            afterEventCouldBe.removeAll(afterEventAre);
            afterEventCouldBe.removeAll(beforeEventAre);
            afterEventCouldBe.remove(selectedOnceEvent);
            try {
                try (java.io.BufferedWriter fout = new java.io.BufferedWriter(new java.io.FileWriter(selectedValue.getName() + ".txt"))) {
                    fout.append(selectedValue.toLongString() + "\n");
                    fout.append("\nafterEventAre:\n");
                    for (Event curEvent : afterEventAre) {
                        fout.append(curEvent.getName() + "\n");
                    }
                    fout.append("\nbeforeEventAre:\n");
                    for (Event curEvent : beforeEventAre) {
                        fout.append(curEvent.getName() + "\n");
                    }
                    fout.append("\nCould Be before or after:\n");
                    for (Event curEvent : afterEventCouldBe) {
                        fout.append(curEvent.getName() + "\n");
                    }
                    fout.flush();
                }
                java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("done");
            } catch (IOException ex) {
                Logger.getLogger(TimeLineEditor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdPrintRelationsActionPerformed

    private void cmdCircleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCircleCheckActionPerformed
        this.mTimeline.resetEvents();
        Collection<Event> Events = this.mTimeline.getEvents();
        for (Event curEvent : Events) {
            if (curEvent instanceof OnceEvent) {
                Collection<OnceEvent> after = new java.util.HashSet<>(this.mTimeline.afterEventAre((OnceEvent) curEvent));
                Collection<OnceEvent> seen = new java.util.ArrayList<>(0);
                boolean seeSelfAfter = false;
                while (!after.isEmpty()) {
                    Iterator<OnceEvent> iterator = after.iterator();
                    OnceEvent next = iterator.next();
                    iterator.remove();
                    if (next.equals(curEvent)) {
                        seeSelfAfter = true;
                        break;
                    } else if (!seen.contains(next)) {
                        seen.add(next);
                        after.addAll(this.mTimeline.afterEventAre(next));
                    }
                }
                seen.clear();
                boolean seeSelfBefore = false;
                Collection<OnceEvent> before = new java.util.HashSet<>(this.mTimeline.beforeEventAre((OnceEvent) curEvent));
                while (!before.isEmpty()) {
                    Iterator<OnceEvent> iterator = before.iterator();
                    OnceEvent next = iterator.next();
                    iterator.remove();
                    if (next.equals(curEvent)) {
                        seeSelfBefore = true;
                        break;
                    } else if (!seen.contains(next)) {
                        seen.add(next);
                        before.addAll(this.mTimeline.beforeEventAre(next));
                    }
                }

                if (seeSelfBefore || seeSelfAfter) {
                    java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info(curEvent.toString());
                }
            }

        }
    }//GEN-LAST:event_cmdCircleCheckActionPerformed

    private void cmdTimeFrameTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimeFrameTestActionPerformed
        new Thread(() -> {
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("resetting events");
            mTimeline.resetEvents();
            int count = 0;
            Map<TimeConstraint, java.lang.Integer> possConstraints = null;
            Map<Event, java.lang.Integer> possEvents = null;
            Stack<EventContainer> Containers = new Stack<>();
            Containers.push(mTimeline);
            int tries = 0;
            while (!Containers.empty()) {
                EventContainer curContainer = Containers.pop();
                curContainer.resetEvents();
                StringBuilder rMessage = new StringBuilder("error in subset:\nEvents:");
                for (Event curEvent : curContainer.getEvents()) {
                    rMessage.append("\n");
                    rMessage.append(curEvent.getName());
                }
                rMessage.append("\nConstraints:");
                for (TimeConstraint curTimeConstraint : curContainer.getConstraints()) {
                    rMessage.append("\n");
                    rMessage.append(curTimeConstraint.toString());
                }
                rMessage.append("\nMessages:");
                curContainer.resetEvents();
                int state1 = 0;
                if (curContainer.applyConstraintsLevel1Sure()) {
                    state1 = UNSATISFIABLE_CONSTRAINTS;
                }
                for (Event curEvent : curContainer.getEvents()) {
                    if (!curEvent.isValid()) {
                        rMessage.append("\ninvalid event: '");
                        rMessage.append(curEvent.getName());
                        rMessage.append("'");
                    }
                }
                if (state1 == 0) {
                    Collection<Event> events = new java.util.ArrayList<>(curContainer.getEvents());
                    double minOfMax = java.lang.Double.MAX_VALUE;
                    while (minOfMax > 10000) {
                        double min = java.lang.Double.MAX_VALUE;
                        double max = 0;
                        OnceEvent maxEvent = null;
                        for (Event curEvent : events) {
                            if (curEvent instanceof OnceEvent) {
                                OnceEvent curOnceEvent = (OnceEvent) curEvent;
                                if (curOnceEvent.getEarliestPossibleStartTime().getYear() != curOnceEvent.getLatestPossibleEndTime().getYear()) {
                                    double size = curEvent.size();
                                    if (size < min) {
                                        min = size;
                                    }
                                    if (size > max) {
                                        maxEvent = curOnceEvent;
                                        max = curEvent.sizeAdj();
                                    }
                                }
                            }
                        }
                        minOfMax = Math.min(minOfMax, max);
                        java.util.Random rnd = new java.util.Random();
                        if ((max > 730) && (maxEvent != null)) {
                            int minYear = maxEvent.getEarliestPossibleStartTime().getYear();
                            int maxYear = maxEvent.getLatestPossibleEndTime().getYear();
                            int diff = maxYear - minYear;
                            int choosenStartYear = minYear;
                            if (diff > 0) {
                                choosenStartYear = minYear + rnd.nextInt(diff);
                            }
                            diff = maxYear - choosenStartYear;
                            int choosenEndYear = choosenStartYear;
                            if (diff > 0) {
                                choosenEndYear = choosenStartYear + rnd.nextInt(diff);
                            }
                            if (maxEvent instanceof OnceDayEvent) {
                                OnceDayEvent minOnceDayEvent = (OnceDayEvent) maxEvent;
                                minOnceDayEvent.setEarliestPossibleDate(new DateTime(choosenStartYear, 1, 1, 1, 0));
                                minOnceDayEvent.setLatestPossibleDate(new DateTime(choosenEndYear, 12, 31, 23, 0));
                            } else if (maxEvent instanceof OncePeriodEvent) {
                                OncePeriodEvent minOncePeriodEvent = (OncePeriodEvent) maxEvent;
                                minOncePeriodEvent.setEarliestPossibleDateForStart(new DateTime(choosenStartYear, 1, 1, 1, 0));
                                minOncePeriodEvent.setLatestPossibleDateForStart(new DateTime(choosenEndYear, 12, 31, 23, 0));
                                minOncePeriodEvent.normalize();
                            }
                        }
                        if (curContainer.applyConstraintsLevel1Sure()) {
                            rMessage.append("\nerror");
                            state1 = Timeline.FAILURE;
                        }
                        events.remove(maxEvent);
                    }
                }
                if (state1 == 0) {
                    Collection<Event> events = curContainer.getEvents();
                    Collection<TimeConstraint> constraints = curContainer.getConstraints();
                    events.stream().forEach((curEvent) -> {
                        curEvent.setUpForComplexEval();
                    });
                    boolean con = true;
                    while (con) {
                        con = false;
                        for (TimeConstraint curTimeConstraint : constraints) {
                            if (!curTimeConstraint.inBeta()) {
                                boolean changedSomething;
                                try {
                                    changedSomething = curTimeConstraint.complexApplyConstraint();
                                } catch (java.lang.Exception ex) {
                                    rMessage.append("\nerror in '");
                                    rMessage.append(curTimeConstraint.toString());
                                    rMessage.append(". Error follows:\n");
                                    rMessage.append(ex.getMessage());
                                    state1 = TVShowTimelineMaker.timeline.Timeline.FAILURE;
                                    con = false;
                                    break;
                                }
                                con = con || changedSomething;
                            }
                        }
                        curContainer.normalizeEvents();
                        for (Event curEvent : events) {
                            if (!curEvent.isValid()) {
                                rMessage.append("\ninvalid event: '");
                                rMessage.append(curEvent.getName());
                                rMessage.append("'");
                                state1 = UNSATISFIABLE_CONSTRAINTS;
                            }
                        }
                    }
                }
                if (state1 == 0) {
                    if (curContainer.applyConstraintsLevel3Sure()) {
                        state1 = UNSATISFIABLE_CONSTRAINTS;
                    }
                    for (Event curEvent : curContainer.getEvents()) {
                        if (!curEvent.isValid()) {
                            rMessage.append("\ninvalid event: '");
                            rMessage.append(curEvent.getName());
                            rMessage.append("'");
                        }
                    }
                }
                if (state1 == UNSATISFIABLE_CONSTRAINTS) {
                    count++;
                    if (possConstraints == null) {
                        possConstraints = new java.util.HashMap<>(curContainer.getConstraints().size());
                        
                        for (TimeConstraint curTimeConstraint : curContainer.getConstraints()) {
                            possConstraints.put(curTimeConstraint, 1);
                        }
                    } else {
                        for (TimeConstraint curTimeConstraint : curContainer.getConstraints()) {
                            possConstraints.put(curTimeConstraint, possConstraints.get(curTimeConstraint) + 1);
                        }
                    }
                    if (possEvents == null){
                        possEvents = new java.util.HashMap<>(curContainer.getEvents().size());
                        for (Event curEvent : curContainer.getEvents()) {
                            possEvents.put(curEvent, 1);
                        }
                    } else {
                        for (Event curEvent : curContainer.getEvents()) {
                            possEvents.put(curEvent, possEvents.get(curEvent) + 1);
                        }
                    }
                    java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info(rMessage.toString());
                    int tempSize = curContainer.getEvents().size();
                    if ((tempSize - 1) >= 2) {
                        int debugMaxMinus = 3;
                        for (int i = 1; ((tempSize - i) >= 2) && (i <= debugMaxMinus); i++) {
                            Containers.push(curContainer.RandomSubSet(tempSize - i));
                        }
                        if ((tempSize * 9 / 10) >= 2) {
                            for (int i = 10; ((tempSize * (i - 1) / i) >= 2) && (i >= 2); i--) {
                                Containers.push(curContainer.RandomSubSet(tempSize * (i - 1) / i));
                            }
                        }
                    }
                    tries = 0;
                } else if (state1 != 0) {
                    if (tries < 10) {
                        Containers.push(curContainer);
                    } else {
                        tries = 0;
                    }
                    tries++;
                } else {
                    tries = 0;
                }
            }
            if ((possConstraints != null) && (possEvents != null)) {
                List<Map.Entry<Event, Integer>> possEventsEntryList = new java.util.ArrayList<>(possEvents.entrySet());
                List<Map.Entry<TimeConstraint, Integer>> possConstraintsEntryList = new java.util.ArrayList<>(possConstraints.entrySet());
                java.util.Collections.sort(possEventsEntryList, new MapIntegerComparator<Event>());
                java.util.Collections.sort(possConstraintsEntryList, new MapIntegerComparator<TimeConstraint>());
                StringBuilder rMessage = new StringBuilder("common events:");
                for (int i = 0; i < 10; i++) {
                    Map.Entry<Event, Integer> curEventEntry = possEventsEntryList.get(i);
                    rMessage.append("\n");
                    rMessage.append(curEventEntry.getKey().getName());
                    rMessage.append(" : ");
                    double percent = curEventEntry.getValue() / (double) count;
                    rMessage.append(percent);
                }
                rMessage.append("\ncommon Constraints:");
                for (int i = 0; i < 10; i++) {
                    Map.Entry<TimeConstraint, Integer> curTimeConstraintEntry = possConstraintsEntryList.get(i);
                    rMessage.append("\n");
                    rMessage.append(curTimeConstraintEntry.getKey().toString());
                    rMessage.append(" : ");
                    double percent = curTimeConstraintEntry.getValue() / (double) count;
                    rMessage.append(percent);
                }
                java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info(rMessage.toString());
            }
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("done");
        }).start();
    }//GEN-LAST:event_cmdTimeFrameTestActionPerformed

    private void cmdRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefreshActionPerformed
        this.refreshConstraints();
    }//GEN-LAST:event_cmdRefreshActionPerformed

    private void cmdBigestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBigestActionPerformed
        int state = 0;
        this.mTimeline.resetEvents();
        while ((!this.mTimeline.ConstraintsSatisfied()) && (state != UNSATISFIABLE_CONSTRAINTS)) {
            //BigO(Constraints.getSize())
            if (this.mTimeline.applyConstraints()) {
                state = UNSATISFIABLE_CONSTRAINTS;
            }
            this.mTimeline.normalizeEvents();
            for (Event curEvent : this.mTimeline.getEvents()) {
                if (!curEvent.isValid()) {
                    state = UNSATISFIABLE_CONSTRAINTS;
                }
            }
        }
        if (state == 0) {
            this.mTimeline.getEvents().stream().filter((curEvent) -> (curEvent instanceof OnceEvent)).forEach((curEvent) -> {
                OnceEvent curOnceEvent = (OnceEvent) curEvent;
                int diff = curOnceEvent.getLatestPossibleEndTime().getYear() - curOnceEvent.getEarliestPossibleStartTime().getYear();
                if (diff >= 1000) {
                    java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info(curEvent.getName());
                }
            });
        }
        java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).info("done");
    }//GEN-LAST:event_cmdBigestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EventTester newEventTester = new EventTester();
        newEventTester.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void refreshConstraints() {
        this.constraintModel = new CollectionListModel<>(this.mTimeline.getConstraints());
        this.listConstraints.setModel(this.constraintModel);
        if (!this.constraintModel.isEmpty()) {
            this.constraintModel.setSelectedItem(this.constraintModel.get(0));
            this.listConstraints.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeLineEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TimeLineEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdApply;
    private javax.swing.JButton cmdBigest;
    private javax.swing.JButton cmdCircleCheck;
    private javax.swing.JButton cmdCreateEvent;
    private javax.swing.JButton cmdDeleteConstraint;
    private javax.swing.JButton cmdDeleteEvent;
    private javax.swing.JButton cmdEditConstraint;
    private javax.swing.JButton cmdEditEvent;
    private javax.swing.JButton cmdPrintPossibleTimeline;
    private javax.swing.JButton cmdPrintRelations;
    private javax.swing.JButton cmdRefresh;
    private javax.swing.JButton cmdResetTimeline;
    private javax.swing.JButton cmdTimeFrameTest;
    private javax.swing.JComboBox<String> comBoxConstraintType;
    private javax.swing.JComboBox<String> comBoxEventTypes;
    private javax.swing.JButton createConstraint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<TimeConstraint> listConstraints;
    private javax.swing.JList<TVShowTimelineMaker.timeline.Event> listEvent;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(TimeLineEditor.class.getName());
}
