/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TVShowTimelineMaker.ui.Joda;

import TVShowTimelineMaker.ui.EditorWindow;
import com.civprod.swing.CollectionListModel;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;
import org.joda.time.Chronology;
import org.joda.time.DateTime;
import org.joda.time.DateTimeField;
import org.joda.time.DateTimeFieldType;
import org.joda.time.Interval;

/**
 *
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class IntervalEditor extends EditorWindow {

    Interval mInterval;
    DateTime mStartDateTime;
    DateTime mEndDateTime;
    private final SpinnerNumberModel mStartSpinnerNumberModel;
    private final SpinnerNumberModel mEndSpinnerNumberModel;
    
    public IntervalEditor(){
        this(new Interval(0,1));
    }
    /**
     * Creates new form IntervalEditor
     * @param inInterval
     */
    public IntervalEditor(Interval inInterval) {
        this.initComponents();
        this.mInterval = inInterval;
        this.mStartDateTime = this.mInterval.getStart();
        this.mEndDateTime = this.mInterval.getEnd();
        CollectionListModel<org.joda.time.DateTimeFieldType> newCollectionListModel = new CollectionListModel<>();
        this.listFields.setModel(newCollectionListModel);
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.centuryOfEra());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.clockhourOfDay());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.clockhourOfHalfday());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.dayOfMonth());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.dayOfWeek());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.dayOfYear());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.era());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.halfdayOfDay());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.hourOfDay());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.hourOfHalfday());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.millisOfDay());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.millisOfSecond());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.minuteOfDay());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.minuteOfHour());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.monthOfYear());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.secondOfDay());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.secondOfMinute());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.weekOfWeekyear());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.weekyear());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.weekyearOfCentury());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.year());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.yearOfCentury());
        newCollectionListModel.add(org.joda.time.DateTimeFieldType.yearOfEra());
        this.mStartSpinnerNumberModel = (javax.swing.SpinnerNumberModel)this.spinValueStart.getModel();
        this.mEndSpinnerNumberModel = (javax.swing.SpinnerNumberModel)this.spinValueEnd.getModel();
        this.txtDateTimeLabel.setText(this.mInterval.toString());
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listFields = new javax.swing.JList<org.joda.time.DateTimeFieldType>();
        spinValueStart = new javax.swing.JSpinner();
        cmdCommit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDateTimeLabel = new javax.swing.JLabel();
        spinValueEnd = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listFields.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listFields.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listFields.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFieldsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listFields);

        spinValueStart.setModel(new javax.swing.SpinnerNumberModel());

        cmdCommit.setText("commit");
        cmdCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCommitActionPerformed(evt);
            }
        });

        jLabel1.setText("overview");

        txtDateTimeLabel.setText("jLabel2");

        spinValueEnd.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinValueStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinValueEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cmdCommit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateTimeLabel)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinValueStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinValueEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cmdCommit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDateTimeLabel))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFieldsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFieldsValueChanged
        DateTimeFieldType mDateTimeFieldType = this.listFields.getSelectedValue();
        Chronology chronology = this.mInterval.getChronology();
        DateTimeField mDateTimeField = mDateTimeFieldType.getField(chronology);
        this.mStartSpinnerNumberModel.setMaximum(mDateTimeField.getMaximumValue());
        this.mStartSpinnerNumberModel.setMinimum(mDateTimeField.getMinimumValue());
        this.mEndSpinnerNumberModel.setMaximum(mDateTimeField.getMaximumValue());
        this.mEndSpinnerNumberModel.setMinimum(mDateTimeField.getMinimumValue());
        this.spinValueStart.setValue(this.mStartDateTime.get(this.listFields.getSelectedValue()));
        this.spinValueEnd.setValue(this.mEndDateTime.get(this.listFields.getSelectedValue()));
    }//GEN-LAST:event_listFieldsValueChanged

    private void cmdCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCommitActionPerformed
        this.mStartDateTime = this.mStartDateTime.withField(this.listFields.getSelectedValue(), (Integer)this.spinValueStart.getValue());
        this.mEndDateTime = this.mEndDateTime.withField(this.listFields.getSelectedValue(), (Integer)this.spinValueEnd.getValue());
        this.mInterval = new Interval(this.mStartDateTime, this.mEndDateTime);
        this.txtDateTimeLabel.setText(this.mInterval.toString());
    }//GEN-LAST:event_cmdCommitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntervalEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IntervalEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCommit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<org.joda.time.DateTimeFieldType> listFields;
    private javax.swing.JSpinner spinValueEnd;
    private javax.swing.JSpinner spinValueStart;
    private javax.swing.JLabel txtDateTimeLabel;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(IntervalEditor.class.getName());
}
