/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TVShowTimelineMaker.ui.ConstraintEditors;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.timeConstraints.ContainsConstraint;
import TVShowTimelineMaker.timeConstraints.interfaces.TimeConstraint;
import TVShowTimelineMaker.timeline.Event;
import TVShowTimelineMaker.timeline.PeriodEvent;
import com.civprod.swing.CollectionListModel;
import java.util.Arrays;
import java.util.logging.Logger;

/**
 *
 * @author Steven Owens
 */
public class ContainsConstraintEditor extends ConstraintEditorWindow {

    @com.civprod.dynamicClassLoading.ClassInitalizer
    public static final void addMe() {
        ConstraintEditorWindow.addConstraintEditor(ContainsConstraint.class, ContainsConstraintEditor.class);
    }
    
    private ContainsConstraint mContainsConstraint;
    /**
     * Creates new form ContainsConstraintEditor
     */
    public ContainsConstraintEditor() {
        this(new ContainsConstraint(Main.myShow.getTimeLine().anyEventOfType(PeriodEvent.class),
                Main.myShow.getTimeLine().getEvents().iterator().next(),
                ContainsConstraint.ContainsType.CONTAINS));
    }
        
    public ContainsConstraintEditor(ContainsConstraint inContainsConstraint) {   
        this.initComponents();
        this.mContainsConstraint = inContainsConstraint;
        CollectionListModel<PeriodEvent> tempModel = new CollectionListModel<>();
        for (Event curEvent : Main.myShow.getTimeLine().getEvents()){
            if (curEvent instanceof PeriodEvent){
                tempModel.add((PeriodEvent) curEvent);
            }
        }
        this.listEvent1.setModel(tempModel);
        this.listEvent2.setModel(new CollectionListModel<>(Main.myShow.getTimeLine().getEvents()));
        CollectionListModel<ContainsConstraint.ContainsType> newCollectionListModel = new CollectionListModel<>();
        this.listType.setModel(newCollectionListModel);
        newCollectionListModel.addAll(Arrays.asList(ContainsConstraint.ContainsType.values()));
        this.listEvent1.setSelectedValue(this.mContainsConstraint.getFirstEvent(), true);
        this.listEvent2.setSelectedValue(this.mContainsConstraint.getSecondEvent(), true);
        this.listType.setSelectedValue(this.mContainsConstraint.getContainsType(), true);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listEvent1 = new javax.swing.JList<TVShowTimelineMaker.timeline.PeriodEvent>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEvent2 = new javax.swing.JList<TVShowTimelineMaker.timeline.Event>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listType = new javax.swing.JList<ContainsConstraint.ContainsType>();
        cmdCreate = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listEvent1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listEvent1);

        listEvent2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listEvent2);

        listType.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listType);

        cmdCreate.setText("create");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCreate)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCreate))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        this.createContainsConstraint();
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.createContainsConstraint();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContainsConstraintEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ContainsConstraintEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCreate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<TVShowTimelineMaker.timeline.PeriodEvent> listEvent1;
    private javax.swing.JList<TVShowTimelineMaker.timeline.Event> listEvent2;
    private javax.swing.JList<ContainsConstraint.ContainsType> listType;
    // End of variables declaration//GEN-END:variables

    private void createContainsConstraint() {
    }
    
    
    @Override
    public TimeConstraint getValue() {
        return this.mContainsConstraint;
    }
    private static final Logger LOG = Logger.getLogger(ContainsConstraintEditor.class.getName());
}
