/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TVShowTimelineMaker.ui.ConstraintEditors;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.timeConstraints.IntervalRelation;
import TVShowTimelineMaker.timeConstraints.interfaces.TimeConstraint;
import TVShowTimelineMaker.timeline.Event;
import TVShowTimelineMaker.timeline.OnceDayEvent;
import com.civprod.swing.CollectionListModel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

/**
 *
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class IntervalRelationEditor extends ConstraintEditorWindow {
    
    @com.civprod.dynamicClassLoading.ClassInitalizer
    public static final void addMe() {
        ConstraintEditorWindow.addConstraintEditor(IntervalRelation.class, IntervalRelationEditor.class);
    }
    
    IntervalRelation mIntervalRelation;
    
     public IntervalRelationEditor() {
        this(new IntervalRelation(Main.myShow.getTimeLine().anyEventOfType(OnceDayEvent.class),
                Main.myShow.getTimeLine().anyEventOfType(OnceDayEvent.class),
                Main.myShow.getTimeLine().anyEventOfType(OnceDayEvent.class),
                Main.myShow.getTimeLine().anyEventOfType(OnceDayEvent.class),
                IntervalRelation.IntervalRelationKind.EQUAL));
    }

    /**
     * Creates new form IntervalRelationEditor
     * @param inIntervalRelation
     */
    public IntervalRelationEditor(IntervalRelation inIntervalRelation) {
        this.initComponents();
        this.mIntervalRelation = inIntervalRelation;
        List<OnceDayEvent> tempModel = new ArrayList<>();
        for (Event curEvent : Main.myShow.getTimeLine().getEvents()){
            if (curEvent instanceof OnceDayEvent){
                tempModel.add((OnceDayEvent) curEvent);
            }
        }
        this.listEvent1.setModel(new CollectionListModel<>(tempModel));
        this.listEvent2.setModel(new CollectionListModel<>(tempModel));
        this.listEvent3.setModel(new CollectionListModel<>(tempModel));
        this.listEvent4.setModel(new CollectionListModel<>(tempModel));
        CollectionListModel<IntervalRelation.IntervalRelationKind> newCollectionListModel = new CollectionListModel<>();
        this.listType.setModel(newCollectionListModel);
        newCollectionListModel.addAll(Arrays.asList(IntervalRelation.IntervalRelationKind.values()));
        this.listEvent1.setSelectedValue(this.mIntervalRelation.getConstrainedEvents()[0], true);
        this.listEvent2.setSelectedValue(this.mIntervalRelation.getConstrainedEvents()[1], true);
        this.listEvent3.setSelectedValue(this.mIntervalRelation.getConstrainedEvents()[2], true);
        this.listEvent4.setSelectedValue(this.mIntervalRelation.getConstrainedEvents()[3], true);
        this.listType.setSelectedValue(this.mIntervalRelation.getKind(), true);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listEvent1 = new javax.swing.JList<OnceDayEvent>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEvent2 = new javax.swing.JList<OnceDayEvent>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listEvent3 = new javax.swing.JList<OnceDayEvent>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listEvent4 = new javax.swing.JList<OnceDayEvent>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listType = new javax.swing.JList<IntervalRelation.IntervalRelationKind>();
        cmdCreate = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listEvent1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listEvent1);

        listEvent2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listEvent2);

        listEvent3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(listEvent3);

        listEvent4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(listEvent4);

        listType.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listType);

        cmdCreate.setText("create");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCreate)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdCreate)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        this.createRelation();
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.createRelation();
    }//GEN-LAST:event_formWindowClosing

    
    private void createRelation() {
        this.mIntervalRelation = new IntervalRelation(this.listEvent1.getSelectedValue(), 
                this.listEvent2.getSelectedValue(), this.listEvent3.getSelectedValue(), 
                this.listEvent4.getSelectedValue(), this.listType.getSelectedValue());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntervalRelationEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IntervalRelationEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCreate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<OnceDayEvent> listEvent1;
    private javax.swing.JList<OnceDayEvent> listEvent2;
    private javax.swing.JList<OnceDayEvent> listEvent3;
    private javax.swing.JList<OnceDayEvent> listEvent4;
    private javax.swing.JList<IntervalRelation.IntervalRelationKind> listType;
    // End of variables declaration//GEN-END:variables

    @Override
    public TimeConstraint getValue() {
        return this.mIntervalRelation;
    }
    private static final Logger LOG = Logger.getLogger(IntervalRelationEditor.class.getName());
}
