/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TVShowTimelineMaker.ui.ConstraintEditors;

import TVShowTimelineMaker.Main;
import TVShowTimelineMaker.timeConstraints.Relation;
import TVShowTimelineMaker.timeConstraints.interfaces.TimeConstraint;
import TVShowTimelineMaker.timeline.Event;
import TVShowTimelineMaker.timeline.OnceEvent;
import TVShowTimelineMaker.ui.Joda.PeriodEditor;
import com.civprod.swing.CollectionListModel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

/**
 *
 * @author Steven Owens
 */
@SuppressWarnings("serial")
public class RelationEditor extends ConstraintEditorWindow {

    @com.civprod.dynamicClassLoading.ClassInitalizer
    public static final void addMe() {
        ConstraintEditorWindow.addConstraintEditor(Relation.class, RelationEditor.class);
    }

    Relation mRelation;
    org.joda.time.ReadablePeriod mPeriod;

    public RelationEditor() {
        this(new Relation(Main.myShow.getTimeLine().anyEventOfType(OnceEvent.class),
                Main.myShow.getTimeLine().anyEventOfType(OnceEvent.class),
                Relation.RelationKind.SAME_TIME_AS));
    }

    /**
     * Creates new form RelationEditor
     *
     * @param inRelation
     */
    public RelationEditor(Relation inRelation) {
        this.initComponents();
        this.mPeriod = inRelation.getTime();
        this.mRelation = inRelation;
        List<OnceEvent> tempModel = new ArrayList<>();
        for (Event curEvent : Main.myShow.getTimeLine().getEvents()){
            if (curEvent instanceof OnceEvent){
                tempModel.add((OnceEvent) curEvent);
            }
        }
        this.listEvent1.setModel(new CollectionListModel<>(tempModel));
        this.listEvent2.setModel(new CollectionListModel<>(tempModel));
        CollectionListModel<Relation.RelationKind> newCollectionListModel = new CollectionListModel<>();
        this.listType.setModel(newCollectionListModel);
        newCollectionListModel.addAll(Arrays.asList(Relation.RelationKind.values()));
        if (this.mRelation.getTime() != null) {
            this.txtDate.setText(this.mRelation.getTime().toString());
        } else {
            this.txtDate.setText("nil");
        }
        this.listEvent1.setSelectedValue(this.mRelation.getFirstEvent(), true);
        this.listEvent2.setSelectedValue(this.mRelation.getSecondEvent(), true);
        this.listType.setSelectedValue(this.mRelation.getKind(), true);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listEvent1 = new javax.swing.JList<TVShowTimelineMaker.timeline.OnceEvent>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEvent2 = new javax.swing.JList<TVShowTimelineMaker.timeline.OnceEvent>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listType = new javax.swing.JList<Relation.RelationKind>();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        cmdCreate = new javax.swing.JButton();
        cdmEditDate = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listEvent1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listEvent1);

        listEvent2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEvent2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listEvent2);

        listType.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listType);

        jLabel1.setText("date(this isn't used in all kinds)");

        txtDate.setText("nil");

        cmdCreate.setText("create");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });

        cdmEditDate.setText("edit date");
        cdmEditDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmEditDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCreate))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdmEditDate)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate)
                    .addComponent(cdmEditDate))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        this.createRelation();
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void createRelation() {
        this.mRelation = new Relation(this.listEvent1.getSelectedValue(), this.listEvent2.getSelectedValue(), this.listType.getSelectedValue(), this.mPeriod);
        if (!mRelation.isValid()){
            this.mRelation = new Relation(this.listEvent1.getSelectedValue(), this.listEvent2.getSelectedValue(), this.listType.getSelectedValue(), new org.joda.time.MutablePeriod(0,org.joda.time.PeriodType.days()));
        }
    }
    private void cdmEditDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmEditDateActionPerformed
        this.setVisible(false);
        final PeriodEditor newPeriodEditor = new PeriodEditor();
        newPeriodEditor.setVisible(true);
        final RelationEditor tempThis = this;
        newPeriodEditor.runOnClose(new Runnable() {
            @Override
            public void run() {
                tempThis.mPeriod = newPeriodEditor.mMutablePeriod;
                tempThis.setVisible(true);
            }
        });
    }//GEN-LAST:event_cdmEditDateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.createRelation();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelationEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RelationEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdmEditDate;
    private javax.swing.JButton cmdCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<TVShowTimelineMaker.timeline.OnceEvent> listEvent1;
    private javax.swing.JList<TVShowTimelineMaker.timeline.OnceEvent> listEvent2;
    private javax.swing.JList<Relation.RelationKind> listType;
    private javax.swing.JLabel txtDate;
    // End of variables declaration//GEN-END:variables

    @Override
    public TimeConstraint getValue() {
        return this.mRelation;
    }
    private static final Logger LOG = Logger.getLogger(RelationEditor.class.getName());
}
